# Generated by Django 5.2b1 on 2025-03-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezerwations',
            name='participants_count',
            field=models.PositiveIntegerField(default=1, help_text='Podaj liczbę osób biorących udział w spotkaniu.', verbose_name='Liczba uczestników'),
        ),
    ]
