# Generated by Django 5.2b1 on 2025-03-16 20:23

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_events_eventtype_venue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Opis'),
        ),
    ]
