# Generated by Django 5.2b1 on 2025-03-16 20:40

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_eventtype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Opis wydarzenia'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Opis'),
        ),
    ]
