# Generated by Django 5.2b1 on 2025-03-17 17:42

import djmoney.models.fields
import djmoney.models.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_events_price_events_price_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='PLN', help_text='Cena za udział w wydarzeniu', max_digits=10, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Cena od osoby'),
        ),
    ]
