# Generated by Django 5.2b1 on 2025-03-18 15:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_rezerwations_cancellation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezerwations',
            name='cancellation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token anulowania'),
        ),
    ]
