# Generated by Django 5.1.7 on 2025-04-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_rezerwations_cancellation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='reservation_end_time',
            field=models.DateTimeField(blank=True, help_text='Po tej godzinie rezerwacja online nie będzie możliwa.', null=True, verbose_name='Koniec przyjmowania rezerwacji'),
        ),
    ]
