# Generated by Django 5.1.7 on 2025-05-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_events_reservation_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rezerwations',
            name='data_processing_consent',
        ),
        migrations.RemoveField(
            model_name='rezerwations',
            name='marketing_emails_consent',
        ),
        migrations.RemoveField(
            model_name='rezerwations',
            name='privacy_policy_consent',
        ),
        migrations.RemoveField(
            model_name='rezerwations',
            name='reminder_emails_consent',
        ),
        migrations.AddField(
            model_name='rezerwations',
            name='newsletter_consent',
            field=models.BooleanField(default=False, help_text='Chcę zapisać się na newsletter, by otrzymywać informacje o przyszłych wydarzeniach i ofertach specjalnych.', verbose_name='Zapis na newsletter'),
        ),
        migrations.AddField(
            model_name='rezerwations',
            name='regulations_consent',
            field=models.BooleanField(default=False, help_text='Zapoznałem się z regulaminem oraz polityką prywatności', verbose_name='Akceptacja regulaminu i polityki prywatności'),
        ),
    ]
