# Generated by Django 5.1.7 on 2025-05-11 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20250511_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rezerwations',
            name='email',
        ),
        migrations.RemoveField(
            model_name='rezerwations',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='rezerwations',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='rezerwations',
            name='newsletter_consent',
        ),
        migrations.RemoveField(
            model_name='rezerwations',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='rezerwations',
            name='regulations_consent',
        ),
    ]
