# Generated by Django 5.1.7 on 2025-05-11 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('events', '0014_remove_rezerwations_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezerwations',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='accounts.customer', verbose_name='Klient'),
        ),
    ]
