# Generated by Django 5.1.7 on 2025-05-11 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('events', '0015_rezerwations_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rezerwations',
            new_name='Reservations',
        ),
    ]
