# Generated by Django 5.1.7 on 2025-05-15 11:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_rename_rezerwations_reservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data utworzenia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventimage',
            name='created_by_admin',
            field=models.BooleanField(default=False, verbose_name='Utworzone przez administratora'),
        ),
        migrations.AddField(
            model_name='eventimage',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresy IP utworzenia'),
        ),
        migrations.AddField(
            model_name='eventimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji'),
        ),
        migrations.AddField(
            model_name='eventimage',
            name='updated_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresy IP aktualizacji'),
        ),
        migrations.AddField(
            model_name='events',
            name='created_by_admin',
            field=models.BooleanField(default=False, verbose_name='Utworzone przez administratora'),
        ),
        migrations.AddField(
            model_name='events',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresy IP utworzenia'),
        ),
        migrations.AddField(
            model_name='events',
            name='updated_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresy IP aktualizacji'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data utworzenia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventtype',
            name='created_by_admin',
            field=models.BooleanField(default=False, verbose_name='Utworzone przez administratora'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresy IP utworzenia'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='updated_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresy IP aktualizacji'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='created_by_admin',
            field=models.BooleanField(default=False, verbose_name='Utworzone przez administratora'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresy IP utworzenia'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='updated_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresy IP aktualizacji'),
        ),
        migrations.AddField(
            model_name='venue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data utworzenia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='created_by_admin',
            field=models.BooleanField(default=False, verbose_name='Utworzone przez administratora'),
        ),
        migrations.AddField(
            model_name='venue',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresy IP utworzenia'),
        ),
        migrations.AddField(
            model_name='venue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji'),
        ),
        migrations.AddField(
            model_name='venue',
            name='updated_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresy IP aktualizacji'),
        ),
    ]
