# Generated by Django 5.1.7 on 2025-05-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_eventimage_created_at_eventimage_created_by_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='type_of_payments',
            field=models.CharField(choices=[('cash', 'Gotówka na miejscu'), ('blik', 'Przedpłata BLIK - 509553366 (w tytule imię, nazwisko i DATA!)')], default='cash', max_length=10, verbose_name='Typ płatności'),
        ),
    ]
