# Generated by Django 5.1.7 on 2025-05-11 16:59

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nazwisko')),
                ('email', models.EmailField(max_length=254, verbose_name='Adres email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='PL', verbose_name='Numer telefonu')),
                ('regulations_consent', models.BooleanField(default=False, help_text='Zapoznałem się z regulaminem oraz polityką prywatności', verbose_name='Akceptacja regulaminu i polityki prywatności')),
                ('newsletter_consent', models.BooleanField(default=False, help_text='Chcę zapisać się na newsletter, by otrzymywać informacje o przyszłych wydarzeniach i ofertach specjalnych.', verbose_name='Zapis na newsletter')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
            ],
            options={
                'verbose_name': 'Klient',
                'verbose_name_plural': 'Klienci',
                'unique_together': {('email', 'phone_number')},
            },
        ),
    ]
