# Generated by Django 5.1.7 on 2025-05-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customer_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_by_admin',
            field=models.BooleanField(default=False, verbose_name='Utworzone przez administratora'),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresy IP utworzenia'),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji'),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresy IP aktualizacji'),
        ),
    ]
