"""
Django settings for webService project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

from django.template.context_processors import media

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']
ALLOWED_HOSTS = ['seiryuu.atthost24.pl', 'www.seiryuu.atthost24.pl']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "events.apps.EventsConfig",
    "accounts.apps.AccountsConfig",
    'phonenumber_field',
    'honeypot',
    'django_recaptcha',
    # zabezpieczenie honeypot
]

# Konfiguracja TinyMCE
# TINYMCE_JS_URL = 'https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js'

TINYMCE_DEFAULT_CONFIG = {
    'theme': "silver",  # Dodajmy jawnie motyw
    'height': 360,
    'width': 'auto',
    'menubar': False,
    'plugins': '''
        advlist autolink lists link image charmap print preview anchor
        searchreplace visualblocks code fullscreen insertdatetime media table
        paste help wordcount
    ''',
    'toolbar': '''
        undo redo | formatselect | bold italic backcolor |
        alignleft aligncenter alignright alignjustify |
        bullist numlist outdent indent | removeformat |
        link image table | code
    ''',
    'content_style': 'body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, '
                     'sans-serif; font-size: 16px; }',
    'language': 'pl',  # Dodałem język polski
    'browser_spellcheck': True,
}

TINYMCE_SPELLCHECKER = True
TINYMCE_COMPRESSOR = False


def honeypot_verifier(value):
    """Własny weryfikator honeypot - zwraca True jeśli pole jest puste"""
    return value == ''


# Konfiguracja ustawień honeypot
HONEYPOT_FIELD_NAME = 'website_url'  # Nazwa ukrytego pola
HONEYPOT_VALUE = ''  # Oczekiwana wartość (puste pole)
HONEYPOT_VERIFIER = honeypot_verifier  # Walidator
# HONEYPOT_RESPONSE = 'Formularz zawiera podejrzane dane. Jeśli nie jesteś botem, spróbuj ponownie.'  # Komunikat błędu

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.IPAddressMiddleware',
    'honeypot.middleware.HoneypotMiddleware',
]

ROOT_URLCONF = 'webService.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'webService.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'pl-pl'

TIME_ZONE = 'Europe/Warsaw'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

# Dodaj te linie
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Opcjonalnie, ale zalecane - określa dodatkowe miejsca, gdzie Django szuka plików statycznych
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Ustawienia domyślne dla email (bezpieczna konfiguracja dla deweloperów)
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# EMAIL_HOST = 'smtp.example.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = ''
# EMAIL_HOST_PASSWORD = ''
# DEFAULT_FROM_EMAIL = 'example@example.com'

# Ustawienia dla plików mediów
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

try:
    from webService.local_settings import *
except ImportError:
    pass

# URL bazowy strony (używany do generowania pełnych linków)
SITE_URL = 'http://seiryuu.atthost24.pl'  # Zmień na rzeczywisty URL w produkcji

# Bezpieczeństwo
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Opcjonalne ustawienia dla developmentu
# W środowisku testowym możesz używać kluczy testowych Google:

# Na końcu pliku settings.py dodaj:
# SILENCED_SYSTEM_CHECKS = ['django_recaptcha.recaptcha_test_key_error']

# if DEBUG:
#     RECAPTCHA_PUBLIC_KEY = '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI'
#     RECAPTCHA_PRIVATE_KEY = '6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe'
